### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by r-barnes** [zhouguiyun-uestc/ParallelFlowDirections#1]
Please add a license file. https://choosealicense.com/ can help with choosing one.

(This is Richard from Computers & Geosciences; I'll be one of your reviewers.)

**Comment by r-barnes** [comment]
(I generally follow the JOSS guidelines [here](https://joss.readthedocs.io/en/latest/review_criteria.html) and [here](https://joss.readthedocs.io/en/latest/review_checklist.html) when reviewing software.)

**Comment by zhouguiyun-uestc** [comment]
done!
