### ISSUE TITLE
cereal as submodule

### ISSUE THREAD

**Issue by r-barnes** [zhouguiyun-uestc/ParallelFlowDirections#10]
Can cereal be included as a submodule rather than directly? This would make it easier to update over time if there are upstream bug fixes.

**Comment by zhouguiyun-uestc** [comment]
Cereal is placed in a separate folder. So it should be very easy to update the code when it is updated. Our sample code primarily serves to provide readers to some codes that they can test and run.  So how cereal is used in our codes should not be a big issue to  the general readers.

**Comment by r-barnes** [comment]
My experience has been that the "sample code" inevitably becomes "the only code", so it's important that it be as clean as possible.

**Comment by zhouguiyun-uestc** [comment]
Cereal has been removed from the source code. Users will need to provide the correct path of codes of cereal in the CMakeLists.txt file.

**Comment by r-barnes** [comment]
My preference is still for cereal as a submodule, but if you prefer not to include it, perhaps you could add a note reminding the user to install it with:
```
sudo apt install libcereal-dev
```
if they are using a Debian-based system.

Doing this on my machine does make compilation possible even with:
```
#Add the cereal libraty path
include_directories(/share/home/cereal/include)
```
Removed from the cmake file, so you may be able to just drop those lines from cmake.

**Comment by zhouguiyun-uestc** [comment]
Done!

**Comment by r-barnes** [comment]
Thanks!
