### ISSUE TITLE
Code doesn't build

### ISSUE THREAD

**Issue by r-barnes** [zhouguiyun-uestc/ParallelFlowDirections#13]
Running `make` yields the error:
```
mpic++ -c -o src/common/tool.o src/common/tool.cpp -I./include/ -I./src/flowdir/ -I./ -std=c++11 -fpermissive -O3
In file included from src/common/tool.cpp:13:
./include/paradem/gdal.h:5:10: fatal error: gdal_priv.h: No such file or directory
    5 | #include <gdal_priv.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
```
Using `cmake` will fix this.

**Comment by zhouguiyun-uestc** [comment]
The gdal_priv.h is not installed by default. So please copy this head file from GDAL source codes to its install folder. It will be found by gcc.

**Comment by r-barnes** [comment]
Copying `gdal_priv.h` to a local directory is a very non-standard compilation procedure. It would be much better to use a more robust, standard solution such as cmake's [FindGDAL](https://cmake.org/cmake/help/v3.14/module/FindGDAL.html).

**Comment by zhouguiyun-uestc** [comment]
done!  We have uploaded the document CMakeLists.txt.

**Comment by r-barnes** [comment]
Thanks, I appreciate this.
