### ISSUE TITLE
Out-of-source build

### ISSUE THREAD

**Issue by r-barnes** [zhouguiyun-uestc/ParallelFlowDirections#17]
The README currently recommends an in-place build. An out-of-source build is preferable can can be achieved with:
```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
make
```
Note that `RelWithDebInfo` compiles the code with optimizations and debugging info (the latter doesn't slow the code down).

**Comment by zhouguiyun-uestc** [comment]
done!

**Comment by r-barnes** [comment]
Thanks!
