### ISSUE TITLE
List source files explicitly

### ISSUE THREAD

**Issue by r-barnes** [zhouguiyun-uestc/ParallelFlowDirections#18]
The cmake file currently uses `aux_source_directory`. The documentation for this says:
> It is tempting to use this command to avoid writing the list of source files for a library or executable target. While this seems to work, there is no way for CMake to generate a build system that knows when a new source file has been added. Normally the generated build system knows when it needs to rerun CMake because the CMakeLists.txt file is modified to add a new source. When the source is just added to the directory without modifying this file, one would have to manually rerun CMake to generate a build system incorporating the new file.

Therefore, please do not use this command and instead list source files (see PR).

**Comment by zhouguiyun-uestc** [comment]
Thanks, done!

**Comment by r-barnes** [comment]
Thanks!

**Comment by r-barnes** [comment]
The problem isn't actually fixed. Source files should be in the same directory or subdirectories of the file 
 containing `CMakeLists.txt` and identified by relative paths. The `${PROJECT_SOURCE_DIR}/ParaDEM/` breaks generation on my machine. See #19 for an example of how to do this correctly.

**Comment by zhouguiyun-uestc** [comment]
Sorry, it was my mistake. Done!

**Comment by r-barnes** [comment]
It seems fixed now, though I'd still recommend replacing, e.g. `${PROJECT_SOURCE_DIR}/src/flowdir/main.cpp` with `src/flowdir/main.cpp`. As far as I'm aware, they should do the same thing, but one gives a less cluttered looking CMakeLists.txt. Feel free to correct me if I'm mistaken.

**Comment by zhouguiyun-uestc** [comment]
Thansk. Done!
