### ISSUE TITLE
Describe input files

### ISSUE THREAD

**Issue by r-barnes** [zhouguiyun-uestc/ParallelFlowDirections#3]
Please explain in the README file what the format of the input arguments should be.

For instance "Input is a text file, which includes the paths of the DEM" is not clear.

While this duplicates somewhat the code, it is useful for people unfamiliar with the language and broadens the impact of your work.

**Comment by zhouguiyun-uestc** [comment]
Done

**Comment by r-barnes** [comment]
Thanks!
