### ISSUE TITLE
cmake

### ISSUE THREAD

**Issue by r-barnes** [zhouguiyun-uestc/ParallelFlowDirections#4]
If possible, please use cmake for your build system as it increases cross-platform compatibility.

An example cmake file from my own work is [here](https://github.com/r-barnes/Barnes2020-FillSpillMerge/blob/master/CMakeLists.txt).

**Comment by zhouguiyun-uestc** [comment]
We agree that CMake is widely used for cross-platform projects.  Since our codes was tested primarily on Linux, we initially provided and tested the makefile.  We will provide and test cmake configurations later on.

**Comment by r-barnes** [comment]
Please comment here when you have done so.

**Comment by zhouguiyun-uestc** [comment]
done!

**Comment by r-barnes** [comment]
Thanks!
