### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by r-barnes** [zhouguiyun-uestc/ParallelFlowDirections#6]
Please remove commented-out code (e.g. https://github.com/zhouguiyun-uestc/ParallelFlowDirections/blob/master/include/paradem/memory.h#L12-L44) if it's not needed anymore or put it in #ifdef/#endif guards with well-documented functionality if it's needed for particular tests.

**Comment by r-barnes** [comment]
https://github.com/zhouguiyun-uestc/ParallelFlowDirections/blob/master/src/common/grid.cpp#L11-L14

**Comment by r-barnes** [comment]
https://github.com/zhouguiyun-uestc/ParallelFlowDirections/blob/master/src/common/memory.cpp#L22-L27

**Comment by r-barnes** [comment]
https://github.com/zhouguiyun-uestc/ParallelFlowDirections/blob/master/src/common/tool.cpp#L21-L22

**Comment by r-barnes** [comment]
https://github.com/zhouguiyun-uestc/ParallelFlowDirections/blob/master/src/common/tool.cpp#L62-L65

**Comment by r-barnes** [comment]
https://github.com/zhouguiyun-uestc/ParallelFlowDirections/blob/master/src/common/tool.cpp#L222-L264

**Comment by zhouguiyun-uestc** [comment]
Done!

**Comment by r-barnes** [comment]
Thanks! I'll mark this as closed, but another issue will be opened if there's dead code elsewhere in the code base.
