### ISSUE TITLE
Eliminate empty destructors

### ISSUE THREAD

**Issue by r-barnes** [zhouguiyun-uestc/ParallelFlowDirections#7]
Empty destructors (e.g. https://github.com/zhouguiyun-uestc/ParallelFlowDirections/blob/master/src/common/grid.cpp#L11-L14) can be replaced with `ClassName::~ClassName() = default` in the header, or eliminated entirely.

**Comment by r-barnes** [comment]
https://github.com/zhouguiyun-uestc/ParallelFlowDirections/blob/master/src/common/tile_info.cpp#L9-L11

**Comment by r-barnes** [comment]
And constructors: https://github.com/zhouguiyun-uestc/ParallelFlowDirections/blob/master/src/flowdir/GridCell.cpp#L5-L7

**Comment by r-barnes** [comment]
https://github.com/zhouguiyun-uestc/ParallelFlowDirections/blob/master/src/flowdir/GridCell.cpp#L14-L16

**Comment by r-barnes** [comment]
https://github.com/zhouguiyun-uestc/ParallelFlowDirections/blob/master/src/flowdir/consumer_2_producer.cpp#L2-L8

**Comment by zhouguiyun-uestc** [comment]
Done!

**Comment by r-barnes** [comment]
Thanks!
